#!/bin/bash

DIRNAME=$(dirname "$0")
SCRIPT_PATH=$(cd "$DIRNAME"; pwd -P)

QUEUE="$1"
shift 1
. "$SCRIPT_PATH/config"
if [ -e "$SCRIPT_PATH/config.$QUEUE" ]; then
    . "$SCRIPT_PATH/config.$QUEUE"
fi

ssh "$USERNAME"@"$REMOTE_HOST" "REMOTE=\"$REMOTE_HTTK_DIR\"; mkdir -p \"\${REMOTE/#~/\$HOME}/Runs/default/ht.taskmgrstats\""

# Safety check
if [ -e "$HTTK_DIR/src/httk" ]; then
    echo "Please wait while copying files."    
    rsync --delete -az -r --files-from="$HTTK_DIR/httk.minimal.files"  "$HTTK_DIR" "$USERNAME"@"$REMOTE_HOST":"$REMOTE_HTTK_DIR/httk/"
    if [ "$1" == "--copy-standalone-python" ]; then
	python_files_from="$HTTK_DIR/Standalone_python_interpreter/standalone_python.files"
	# Make sure the files we want to upload exist:
	standalone_dir=`dirname $python_files_from`
	if [ ! -f $standalone_dir/python -o ! -d $standalone_dir/lib ]; then
	    echo ""
	    echo "\"python\" interpreter or the dependency folder \"lib\" could not be"
	    echo "found in \"$standalone_dir\"."
	    echo "Please build the standalone interpreter and try again."
	    echo ""
	    exit 1
	fi
	echo "Copying standalone Python interpreter to \"$REMOTE_HTTK_DIR/standalone_python\"..."
        rsync --delete -az -r --files-from="$python_files_from" "$standalone_dir" "$USERNAME"@"$REMOTE_HOST":"$REMOTE_HTTK_DIR/standalone_python"
    fi
    echo "Installation complete."
    echo ""
else
    echo "Failure to install code due to configuration error ($HTTK_DIR/src/httk does not exist.)." >&2
fi
