#!/bin/bash

DIRNAME=$(dirname "$0")
SCRIPT_PATH=$(cd "$DIRNAME"; pwd -P)

QUEUE="$1"
shift 1
. "$SCRIPT_PATH/config"
if [ -e "$SCRIPT_PATH/config.$QUEUE" ]; then
    . "$SCRIPT_PATH/config.$QUEUE"
fi

rsync -az -r --delete --files-from=- "$USERNAME"@"$REMOTE_HOST":"$REMOTE_HTTK_DIR"/Runs/"$QUEUE"/"$1" "$2"
