#!/bin/bash

DIRNAME=$(dirname "$0")
SCRIPT_PATH=$(cd "$DIRNAME"; pwd -P)
. "$SCRIPT_PATH/config"

QUEUE="$1"
shift 1
. "$SCRIPT_PATH/config"
if [ -e "$SCRIPT_PATH/config.$QUEUE" ]; then
    . "$SCRIPT_PATH/config.$QUEUE"
fi

if [ -n "$1" ]; then
    NUMBER="$1"
else
    NUMBER="1"
fi

(cat - <<EOF
#!/bin/bash
#SBATCH -A $SLURM_PROJECT
#SBATCH -N $SLURM_NODES
#SBATCH -t $SLURM_TIMEOUT

VASP_PSEUDO_PATH="$VASP_PSEUDO_PATH"
REMOTE_HTTK_DIR="$REMOTE_HTTK_DIR"

export HT_NBR_NODES="\$((SLURM_JOB_NUM_NODES*SLURM_TASKS_PER_NODE))"
export VASP_PSEUDOLIB=\${VASP_PSEUDO_PATH/#\~/\$HOME}
export HTTK_BASE_DIR=\${REMOTE_HTTK_DIR/#\~/\$HOME}
export HTTK_DIR=\$HTTK_BASE_DIR/httk
export VASP_EXECUTE="$VASP_COMMAND"

DATE=\$(date +"%Y-%m-%d_%H.%M.%S")
INITIAL=\$(pwd -P)
HOSTNAME=\$(hostname)

echo "RUN STARTS: \$DATE in dir \$INITIAL on node: \$HOSTNAME"

source "\$HTTK_DIR/init.shell"

"\$HTTK_DIR/Execution/taskmanager.sh" -d .. -t "$TASKMGR_JOB_TIMEOUT"

ENDDATE=\$(date +"%Y-%m-%d_%H.%M.%S")
echo "RUN ENDS: \$ENDDATE"
EOF
) | ssh "$USERNAME"@"$REMOTE_HOST" "mkdir -p \"${REMOTE_HTTK_DIR/#\~\//}/Runs/\"$QUEUE\"/ht.taskmgrstats\"; cd \"${REMOTE_HTTK_DIR/#\~\//}/Runs/\"$QUEUE\"/ht.taskmgrstats\"; cat - > ht.tmp.batch.q; for (( i=0; i<$NUMBER; i++)); do sbatch ht.tmp.batch.q; done"
