#!/bin/bash

DIRNAME=$(dirname "$0")
SCRIPT_PATH=$(cd "$DIRNAME"; pwd -P)
if [ -e "$SCRIPT_PATH/config" ]; then
    . "$SCRIPT_PATH/config"
fi

function readdata {
    DEFAULT=$1
    read DATA
    if [ -n "$DATA" ]; then
	echo "$DATA"
    else
	echo "$DEFAULT"
    fi
}

echo "Directory for keeping ongoing local httk runs: [$LOCAL_HTTK_DIR]"
LOCAL_HTTK_DIR=$(readdata "$LOCAL_HTTK_DIR")
echo

if [ "${LOCAL_HTTK_DIR:0:1}" = "/" -o "${LOCAL_HTTK_DIR:0:1}" = "~" ]; then
    LOCAL_HTTK_DIR="$LOCAL_HTTK_DIR"
else
    LOCAL_HTTK_DIR="~/$LOCAL_HTTK_DIR"
fi

echo "Command to run vasp: [$VASP_COMMAND]"
VASP_COMMAND=$(readdata "$VASP_COMMAND")
echo 

echo "Vasp pseudopotential path: [$VASP_PSEUDO_PATH]"
VASP_PSEUDO_PATH=$(readdata "$VASP_PSEUDO_PATH")
echo

if [ "${VASP_PSEUDO_PATH:0:1}" = "/" -o "${VASP_PSEUDO_PATH:0:1}" = "~" ]; then
    VASP_PSEUDO_PATH="$VASP_PSEUDO_PATH"
else
    VASP_PSEUDO_PATH="~/$VASP_PSEUDO_PATH"
fi

echo "Slurm project to submit jobs to: [$SLURM_PROJECT]"
SLURM_PROJECT=$(readdata "$SLURM_PROJECT")

echo "Slurm queue to submit jobs to [$SLURM_QUEUE]"
SLURM_QUEUE=$(readdata "$SLURM_QUEUE")

echo "Slurm job timeout [$SLURM_TIMEOUT]"
SLURM_TIMEOUT=$(readdata "$SLURM_TIMEOUT")

echo "Taskmanager timeout max time per task in seconds: [$TASKMGR_JOB_TIMEOUT]"
TASKMGR_JOB_TIMEOUT=$(readdata "$TASKMGR_JOB_TIMEOUT")

cat - > config <<EOF
LOCAL_HTTK_DIR="$LOCAL_HTTK_DIR"
VASP_COMMAND="$VASP_COMMAND"
VASP_PSEUDO_PATH="$VASP_PSEUDO_PATH"
SLURM_PROJECT="$SLURM_PROJECT"
SLURM_QUEUE="$SLURM_QUEUE"
SLURM_NODES="1"
SLURM_TIMEOUT="$SLURM_TIMEOUT"
TASKMGR_JOB_TIMEOUT="$TASKMGR_JOB_TIMEOUT"
EOF
