clean:
	rm -f */findsym.log */*~ *~ 4_database/example.sqlite 1_simple_things/PbTiO3*.vasp 1_simple_things/PbTiO3*.cif
	rm -rf 5_calculations/Run 5_calculations/Runs
	rm -rf 6_website/1_static_simple/public
	rm -rf 6_website/2_static_rst_templator/public
	rm -rf 6_website/3_hello_world_app/public
	rm -rf 6_website/4_search_app/public
	rm -rf 8_elastic_constants/elastic_constants.sqlite
	rm -rf 8_elastic_constants/Runs
	rm -rf 8_elastic_constants/Runs_finished
	rm -rf 9_duckdb/sample.duckdb
	rm -rf 9_duckdb/duckdb
	rm -rf 9_duckdb/Runs_finished

